### ISSUE TITLE
can you include a working example project

### ISSUE THREAD

**Issue by andrew-oko-odion** [bjoluc/next-redux-cookie-wrapper#1]
Hey can you include a working example, most people usually have slightly different configuration on their nextjs project. so one can see how to adapt theirs.

**Comment by bjoluc** [comment]
The whole point of this package being a drop-in replacement is that it works with the same setup as next-redux-wrapper. There is already a working example in the next-redux-wrapper docs, which I linked in the [setup](https://github.com/bjoluc/next-redux-cookie-wrapper#setup) section. I personally do believe that copy-pasting their example into this project's Readme would unnecessarily bloat up the documentation (the example code snippet is rather large).

Closing this as won't fix. Feel free to re-open this issue if you disagree.

**Comment by efstathiosntonas** [comment]
Thanks for providing this module!!

Can you please share an example with a custom server.js?

**Comment by bjoluc** [comment]
Hey, glad you found it!
There's nothing special about using a custom server.js. This package only wraps the App component in `_app.js` and does not require any special setup apart from that. You could basically just use the [custom server example](https://github.com/zeit/next.js/tree/canary/examples/custom-server) and add then follow the [setup](https://github.com/bjoluc/next-redux-cookie-wrapper#setup) instructions. Happy coding!

**Comment by bjoluc** [comment]
Sorry @andrew-oko-odion for beeing a bit harsh back then! Guess I didn't fully get the question; definitely changed my mind on this one! v2 includes a `demo` directory now for folks to tinker around with :slightly_smiling_face:
