### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by MaciejWiatr** [bjoluc/next-redux-cookie-wrapper#11]
I would love to see example project using this library, it would be very helpful for newcomers (like me :D)

**Comment by bjoluc** [comment]
Hi Maciej,
it seems that @ZhengYuTay has created a little [with-redux-cookie-wrapper](https://github.com/ZhengYuTay/with-redux-cookie-wrapper) example that might help you to get started (thanks for that @ZhengYuTay!). Basically, you only need a custom `_app.js/ts` to set up next-redux-cookie-wrapper, along with some `makeStore()` method described in the [next-redux-wrapper v5 docs](https://github.com/kirill-konshin/next-redux-wrapper/tree/5.x#installation). Let me know if you're facing any problems :)
