### ISSUE TITLE
Example with js and without redux-toolkit

### ISSUE THREAD

**Issue by Goldyukol** [bjoluc/next-redux-cookie-wrapper#15]
Please post an example for simple js and no redux-toolkit

**Comment by bjoluc** [comment]
Hi @Goldyukol,
I'm afraid a non-typescript example is currently not on my agenda, but you can use the [TS Playground](https://www.typescriptlang.org/play/) to get rid of the typescript overhead. For the non-redux-toolkit demo, I'd like to refer you to the [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper/tree/master/packages/demo-page) demo in conjunction with the [setup section](https://github.com/bjoluc/next-redux-cookie-wrapper#setup) which is toolkit-free (and plain js by the way).
If you are facing any problems related to this package, feel free to reach out to me via this issue!
