### ISSUE TITLE
Disabling compression of cookie values

### ISSUE THREAD

**Issue by bananamboon** [bjoluc/next-redux-cookie-wrapper#18]
Why the value store in cookies being decode?

**Comment by bjoluc** [comment]
Because they are encoded? :stuck_out_tongue:
> Some words about compression: The serialized cookie state is compressed using lz-string to keep the cookie size small. Currently, there is no way to disable compression. If you would like to see one implemented, please let me know.

Are you interested in disabling compression?

**Comment by bananamboon** [comment]
yes please

**Comment by bananamboon** [comment]
okkay thankyou, let me know if theres update to disable compression.
