### ISSUE TITLE
Question: Authentication

### ISSUE THREAD

**Issue by bryantobing12** [bjoluc/next-redux-cookie-wrapper#33]
- Is this library safe for saving auth token in cookies?

**Comment by bjoluc** [comment]
You can use this library to store and parse the auth token in/from a cookie, yes. Whether you consider that secure depends on whether you trust cookies and your client/server side redux store (I'd recommend setting the `secure` flag for your cookie to avoid accidentally exposing it via plain HTTP). Using this library – to the best of my knowledge – won't introduce any attack surface compared to programmatically setting/reading an auth token cookie on the client and server, if that's what you mean.
