### ISSUE TITLE
Error: Text content does not match server-rendered HTML in newer NextJS version

### ISSUE THREAD

**Issue by heinthanth** [bjoluc/next-redux-cookie-wrapper#36]
I've cloned the repo ( demo repo ). Upgraded all dependencies. And the demo no longer works resulting in Content mis-match as below.

<img width="1552" alt="Screen Shot 2022-06-17 at 3 37 24 PM" src="https://user-images.githubusercontent.com/43804263/174266735-2d7aa462-2635-4d39-882e-a311c3fdacc3.png">

The clean ( fresh ) NextJS application also not working.

**Comment by heinthanth** [comment]
Clean demo ( with Next 12 and Wrapper 7 ) also not working.

**Comment by uwemneku** [comment]
@heinthanth calling `wrapper.getInitialPageProps((store) => () => {})` in pages without getSeverSideProps fixed this issue for me

**Comment by heinthanth** [comment]
Oh ... interesting ... I think we can do that in `_app.tsx` too. Calling that in every pages seems duplicated.

My use-case is that, I store site settings ( locale, theme ) in cookie and if user request dark theme, dark theme is responded from server side, So that, user won't see flashes, etc.

**Comment by heinthanth** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/43804263/184069368-bd86589b-f432-40a1-9554-27953c4837e5.png">

Yeah, I added something like this and it works.

**Comment by uwemneku** [comment]
@heinthanth This definately looks neater. My only concern is that next js docs gives this [waring](https://nextjs.org/docs/advanced-features/custom-app)

> This disables the ability to
> // perform automatic static optimization, causing every page in your app to
> // be server-side rendered

Although from the [How it works](https://github.com/kirill-konshin/next-redux-wrapper#how-it-works) documentation for next-redux-wrapper, it does mention that `getInitialProps` is called in _app.js so maybe this concern is not valid

**Comment by bjoluc** [comment]
Hi both,

the runtime error is thrown by React v18. When Next.js pre-renders a page, no client cookies are available (the page is rendered for all clients after all). Hence, the default state is included in the server-rendered HTML, whereas the initial client render has access to the client's cookies and thus differs from the server render. There's nothing we can really do about this, except for server-rendering affected pages per-client (using `getServerSideProps` or `getInitialProps`). The mismatch error only occurs on the page that is initially loaded though, so I think I'll add a `"/" => "/ssr/1"` redirect to the demo to circumvent it in the demo project.

Your concern is right @uwemneku, `getInitialProps` in `_app.js` disables automatic static optimization so the page is server-rendered for each request individually. I'd consider it only as a last resort...

**Comment by heinthanth** [comment]
Yeah ... I think I should close this issue now. @bjoluc's answer does make sense.
