### ISSUE TITLE
What happens if we store subtrees in cookie whose size exceeds 4096 bytes ?

### ISSUE THREAD

**Issue by phatify** [bjoluc/next-redux-cookie-wrapper#46]
what happens if we store subtrees in cookie whose size exceeds 4096 bytes ?
Is that an efficient way to persist state?

![image](https://user-images.githubusercontent.com/70096611/204086241-252135a1-dd26-4b48-bbc4-e9644ad72ad6.png)

**Comment by bjoluc** [comment]
> what happens if we store subtrees in cookie whose size exceeds 4096 bytes ?

I don't know how browsers handle this in particular, but chances are something will go wrong when saving the cookie...

> Is that an efficient way to persist state?

For large amounts of state, you should consider using [Redux Persist](https://github.com/kirill-konshin/next-redux-wrapper#usage-with-redux-persist). You could technically split large subtrees into multiple cookies, but that doesn't make cookies any more efficient. Alternatively, if you can infer pieces of your state (for instance by loading them from a database), it may be an option to sync relevant state portions with cookies and just dynamically fetch missing pieces.
