### ISSUE TITLE
Problem of hydration from the cookie data

### ISSUE THREAD

**Issue by juliengueperoux** [bjoluc/next-redux-cookie-wrapper#50]
Hi,

I am facing an issue on a personal project. I am calling an API to have my data into `getServerSideProps` in the `index.tsx`.
My goal is to save the data into a cookie so that I wouldn't have to call the API each time the user reload the page.

Thing is, I am all the time facing this error on page load : `Error: Hydration failed because the initial UI does not match what was rendered on the server.`

It is like the data retrieved from the api call was cleaned and deleted from the store after page load on the SSR...
I mean, the hydration from the data received during SSR are not set in the CSR store

I am new to Nextjs and I would love to have your help :)

package.json 
<img width="359" alt="Capture d’écran 2023-03-17 à 09 19 39" src="https://user-images.githubusercontent.com/43140055/225850729-647f1898-75a5-48cc-a80e-34174cd212f9.png">

store.ts
<img width="534" alt="Capture d’écran 2023-03-17 à 09 22 29" src="https://user-images.githubusercontent.com/43140055/225851358-1e23c111-2be8-4f38-822f-b070fd1ec524.png">

index.tsx
<img width="485" alt="Capture d’écran 2023-03-17 à 09 23 20" src="https://user-images.githubusercontent.com/43140055/225851530-2978ceb3-8c3e-4b8a-b1ef-6d6db879c6ae.png">

fishesSlice.ts
<img width="491" alt="Capture d’écran 2023-03-17 à 09 21 18" src="https://user-images.githubusercontent.com/43140055/225851186-00d3d562-0604-4b3a-bdb5-c994539204a5.png">

**Comment by bjoluc** [comment]
Hi @juliengueperoux,

I'm glad to see you seem to have solved your problem.

> My goal is to save the data into a cookie so that I wouldn't have to call the API each time the user reload the page.

This sounds like a perfect fit for `getStaticProps`: If you dispatch `setFishes` there, next-redux-wrapper will hydrate your client store with the fishes and the API will only be called at build time (or when regenerating) – no need to store `fishes` in a cookie then.
