### ISSUE TITLE
Sync client state with cookies

### ISSUE THREAD

**Issue by AndyW22** [bjoluc/next-redux-cookie-wrapper#51]
Is there any way to sync the client state with the state defined in the cookies? Currently it is only set/updated during SSR.

This could be useful if you wanted to skip fetching certain data that has to be fetched on the client by keeping it in the state and will be already available on page load.

**Comment by bjoluc** [comment]
> Currently it is only set/updated during SSR.

I'd assume that's because you only update state during SSR? `next-redux-cookie-wrapper` updates the cookies when relevant client state changes – check it out in the demo by clicking the "Increase counter" button :)

**Comment by AndyW22** [comment]
> > Currently it is only set/updated during SSR.
> 
> I'd assume that's because you only update state during SSR? `next-redux-cookie-wrapper` updates the cookies when relevant client state changes – check it out in the demo by clicking the "Increase counter" button :)

I am updating the state client side too, but upon looking again I've realized that the cookie size on load is 3950B and my state updates are setting it above the limit of 4096B so it is not updating. So will need to look into making the cookie a bit smaller. thanks for your help
