### ISSUE TITLE
CookieConfig not being used on client

### ISSUE THREAD

**Issue by Pikachews** [bjoluc/next-redux-cookie-wrapper#7]
I noticed that my cookieConfig settings weren't taking effect on the client, whether it was changing the persist key or the cookie expiration.

The root cause seems to be that the cookieConfigs are only being used on the server.
https://github.com/bjoluc/next-redux-cookie-wrapper/blob/e2616e3d4ebdd472bd04799a01926c915b5e7e19/src/index.tsx#L126-L132

Whereas on the client, no cookieConfig is being used:
https://github.com/bjoluc/next-redux-cookie-wrapper/blob/e2616e3d4ebdd472bd04799a01926c915b5e7e19/src/index.tsx#L164
https://github.com/bjoluc/next-redux-cookie-wrapper/blob/e2616e3d4ebdd472bd04799a01926c915b5e7e19/src/index.tsx#L71

**Comment by bjoluc** [comment]
Wow, the bot was faster than me :smile: Anyway, thanks for pointing this out!

**Comment by Pikachews** [comment]
Thanks for the quick fix!
