### ISSUE TITLE
Next 9.5 Upgrade

### ISSUE THREAD

**Issue by mshez** [bjoluc/next-redux-cookie-wrapper#9]
Next-Redux has been changed. SSG and SSR methods compatibility.

**Comment by bjoluc** [comment]
Thanks for your interest in this lib. Could you elaborate a little?

**Comment by bjoluc** [comment]
Closing this in favor of #13 – stay tuned!

**Comment by bjoluc** [comment]
@mshez Hi there, just a quick note here that I released v2 which supports the new methods!
